"""
********************************************************************************************
* models.py                        |********************************************************
* Developed by: Ryan Hatch         |********************************************************
* Date: August 10th 2022           |********************************************************
* Last Updated: Febuary 13th 2025  |********************************************************
* Version: 6.2-A                   |********************************************************
********************************************************************************************
********************************#* Description: |*******************************************
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
|  models.py is a module that contains the database models for the web-app.                *
*    SQLite / SQLAlchemy to define the models and their relationships. The models are:     *
*       - User: stores the user information.                                               *
*       - Hash: stores the hashes generated by the user.                                   *
*       - EncryptedText: stores the encrypted texts generated by the user.                 *
*       - Key: stores the keys generated by the user.                                      *
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
********************************************************************************************
"""

#* ---------------------- | Import libraries for the web-app | ---------------------- *#
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from dataclasses import dataclass
from db import db

__all__ = ['db', 'User', 'Hash', 'EncryptedText', 'Key', 'PGPKey', 'Wallet', 'Usage', 'Invoice']
#* ---------------------- | Database Models | --------------------- *#
db = SQLAlchemy()

#* ---------------------- | User Model | -------------------------- *#
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # Shared resources for the user
    hashes = db.relationship('Hash', backref='user', lazy=True)                     # hashes, encrypted texts, and keys are linked to the users 'user_id'
    encrypted_texts = db.relationship('EncryptedText', backref='user', lazy=True)   # Related objects are loaded in a single query for efficiency

#* ---------------------- | Hash Model | ------------------------- *#
class Hash(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    hash_value = db.Column(db.String(256), nullable=False)
    salt = db.Column(db.String(256))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

#* ---------------------- | Encrypted Text Model | --------------- *#
class EncryptedText(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    encrypted_content = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

#* ---------------------- | Key Model | ------------------------- *#
class Key(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    key_value = db.Column(db.String(256), nullable=False)
    active = db.Column(db.Boolean, default=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

#* ---------------------- | PGP Key Model | ------------------------- *#
class PGPKey(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    public_key = db.Column(db.Text, nullable=False)
    private_key = db.Column(db.Text, nullable=False)  # Store encrypted
    active = db.Column(db.Boolean, default=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

#* ---------------------- | ECC Key Model | ------------------------- *#
class ECCKey(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    public_key = db.Column(db.Text, nullable=False)
    private_key = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    active = db.Column(db.Boolean, default=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

#* ---------------------- | Processing Job Model | ------------------------- *#
class ProcessingJob(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    status = db.Column(db.String(50), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    completed_at = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    merkle_root = db.Column(db.String(64))
    chunk_count = db.Column(db.Integer)

#* ---------------------- | Solana Dapp Model | ------------------------- *#
class Wallet(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    address = db.Column(db.String(64), unique=True, nullable=False)
    plan = db.Column(db.String(16), default="free")
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

class Usage(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    wallet_id = db.Column(db.Integer, db.ForeignKey("wallet.id"))
    op = db.Column(db.String(16))   # "encrypt"|"decrypt"
    bytes = db.Column(db.Integer)
    ts = db.Column(db.DateTime, default=datetime.utcnow)

class Invoice(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    wallet_id = db.Column(db.Integer, db.ForeignKey("wallet.id"))
    amount_lamports = db.Column(db.Integer)
    reference = db.Column(db.String(88), unique=True)  # Solana Pay reference pubkey
    status = db.Column(db.String(16), default="pending")
    ts = db.Column(db.DateTime, default=datetime.utcnow)